Migrate to node docker base image (#223)
From https://github.com/clearhaus/gateway-api-docs/pull/222 we started
to see failing automatic deploys, see action run
https://github.com/clearhaus/gateway-api-docs/actions/runs/19851253521,
with error:

```
Error: require() of ES Module /root/.yarn/berry/cache/change-case-npm-5.4.4-3eecdb2577-10c0.zip/node_modules/change-case/dist/index.js from /root/.yarn/berry/cache/gulp-awspublish-npm-9.0.0-5454820298-10c0.zip/node_modules/gulp-awspublish/lib/index.js not supported.
Instead change the require of /root/.yarn/berry/cache/change-case-npm-5.4.4-3eecdb2577-10c0.zip/node_modules/change-case/dist/index.js in /root/.yarn/berry/cache/gulp-awspublish-npm-9.0.0-5454820298-10c0.zip/node_modules/gulp-awspublish/lib/index.js to a dynamic import() which is available in all CommonJS modules.
```

This seems to be related to be change from `gulp-awspublish` `^8.0.0` to
`^9.0.0` and
https://github.com/pgherveou/gulp-awspublish/commit/84127050bd9468acc820f29038ac39b42867bb1c.

I haven't been able to validate it locally, but we are not running
outdated versions of `node` or `yarn` after this change.
:crossed_fingers:

Alternatively I'll just downgrade it back to `^8.0.0`.